# select * from customer;
select * from customer limit 10;

-- Q1. Compare the total revenue generated by male customers and female customers.
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Identify customers who applied a discount and still spent more than the overall average purchase amount.
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' 
and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Find the top 5 products with the highest average review ratings.
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Analyze the difference in average purchase amounts between Standard Shipping and Express Shipping.
select shipping_type, 
round(avg(purchase_amount),2) as avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Check whether subscribed customers spend more by comparing both average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
       count(customer_id) AS total_customers,
       round(avg(purchase_amount),2) AS avg_spend,
       round(sum(purchase_amount),2) AS total_revenue
from customer
group by subscription_status
order by total_revenue desc, avg_spend desc;

-- Q6. Determine the 5 products with the highest percentage of purchases where discounts were applied.
select item_purchased,
       round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer)

select customer_segment, count(*) as Number_of_Customers
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
select item_rank, category, item_purchased, total_orders
from (
    select 
        category,
        item_purchased,
        count(customer_id) as total_orders,
        row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from customer
    group by category, item_purchased
) as item_counts
where item_rank <= 3;

-- Q9. Examine whether repeat buyers (customers with more than 5 previous purchases) are also more likely to be subscribers.
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status;

-- 10. Calculate the revenue contribution made by each age group.
select age_group, sum(purchase_amount) as total_revenue from customer
group by age_group
order by total_revenue desc;

